### ISSUE TITLE
Behavior Inconsistent

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint-chromium#13]
Using the following code:
```javascript
Chromium = require('chromium');
var webview = new Chromium();
win.appendChild(webview);
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "file://D://Projects//Tint Tests//Chromium//index.html";
webview.devtools = true;
```
The page does not always load. Much stranger yet, I see different behavior between running
```javascript
tint index.js
```

and

```javascript
tint
> .load index.js
```

The second command seems to work more frequently, but still inconsistently.

The dev tools show no elements on the page and running JS through the dev tools console does not work.

Is there some sort of race condition? Using a setTimeout seems to fix the issue, but it's definitely preferable to load in the page as soon as possible vs enforcing an arbitrary waiting period.

**Comment by trevorlinton** [comment]
@JohnLouderback My guess is its a race condition, there's a IsBrowserInitialized bool on the native chromium instance, i have a feeling if the address is set prior to it fully loading the request gets ignored. Let me dig a little deeper, there's probably a simple solution we can add to the chromium class to fix it.

**Comment by trevorlinton** [comment]
@JohnLouderback Hopefully this should be fixed.  You'll need to build Tint and clone Tint-Chromium then  run 'install.bat' to get this to work. Next monday we'll have v2.1.8 of Tint out that will help resolve these issues, we'll also post the new Tint-Chromium to npm on Monday that should have all the behaviors standardized with the WebView module in Tint. 

Were still cranking away at the remaining bugs in this, feel free to reopen if you have additional problems.
