### ISSUE TITLE
Running code in the Readme closes immediately

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint-chromium#7]
I just ran the code in the readme:
```javascript
require('Common');
Chromium = require('chromium');

var win = new Window();
var webview = new Chromium();
win.appendChild(webview);
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "https://www.trueinteractions.com/tint2/docs/";
win.visible = true;
```

The process dies immediately after opening the window without any error. The webview, in this extremely short period, does not render.

**Comment by JohnLouderback** [comment]
The crash happens when ``win.appendChild(webview);`` is executed. 
This behavior can be seen in the following:
```javascript
require('Common');
Chromium = require('chromium');

var win = new Window();
var webview = new Chromium();
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "https://www.trueinteractions.com/tint2/docs/";
win.visible = true;
var i = 5;
var timeout = setInterval(function(){
	console.log(i);
	if (i === 0) {
		clearInterval(timeout);
		win.appendChild(webview);
	} else {
		i--;
	}
},1000);
```
Immediately after "0" is logged to the console the program quits (or, I assume, crashes, actually).

**Comment by JohnLouderback** [comment]
Don't mean to spam here, but I just wanted to update and say that I'm not seeing any difference after downloading the latest release either. Any suggestions?

**Comment by trevorlinton** [comment]
@JohnLouderback 

It seems this is an issue related to the callbacks from chromium being posted to the wrong thread. I thought we had fixed this but i'm unsure why its creeping back up again.  Within the node_modules/chromium/win/Chromium.js file if you comment out lines 92-97 it should work fine (basically all of the addEventListener on the nativeView).  I'll take a closer look at this; we had to implement a shortcut for WPF threaded events to prevent them from firing out of order when we instituted the threading support for Chromium, I suspect it broke one of the callbacks for Chromium :frowning:

**Comment by JohnLouderback** [comment]
That did it! Thanks for the temporary fix! Checking it out now. Hopefully the thread issue gets fixed. Sounds like hell. Good luck.

**Comment by trevorlinton** [comment]
@JohnLouderback It's a minor bug, i'm nearly ready with a patch. It'll take us a bit to make some unit tests for this however as i'd rather have something notify me during a deploy that it didn't work then have you have to come back to me because we forgot something.

Sorry for the inconvenience, it'll be a couple days before we get this nailed down properly, i'll post status here.

**Comment by JohnLouderback** [comment]
It's no sweat on the wait. That's the nature of new technology. I'm glad you guys take resolving bugs so seriously. A week turn around time for the things you've done is pretty damn phenomenal, in my opinion. Eager to hear back on this. I'll keep testing in the mean time.

**Comment by trevorlinton** [comment]
@JohnLouderback 

We've fixed the multithreading issue and added unit tests for it, you can find the new .exe file (just copy over the existing one in Program Files) here: https://www.trueinteractions.com/tint-2.1.5-fixed-threading.zip  The commits for it are also here: https://github.com/trueinteractions/tint2/commit/8b3a270c238a0470a4acf717d00d73c6d7c0d88d

If you continue to have issues please let me know (and re-open this issue.)
