### ISSUE TITLE
Transparency not working

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint-chromium#8]
With the code: 
```javascript
require('Common');
Chromium = require('chromium');

var win = new Window();
var webview = new Chromium();
win.backgroundColor = 'transparent';
win.frame = false;
win.appendChild(webview);
webview.transparent = true;
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "https://www.trueinteractions.com/tint2/docs/";
win.visible = true;
webview.devtools = true;
```

Neither the window nor the webview are transparent.
Note: I used the debugger to change the background colors to transparent.

**Comment by trevorlinton** [comment]
@JohnLouderback Can you test this again with the latest build at https://www.trueinteractions.com/tint-2.1.5-fixed-threading.zip and let me know if you still have issues?

**Comment by JohnLouderback** [comment]
I must have forgot to close this one. Yep. Transparency is working in this build! The frameless non-transparent windows are still not working correctly though.
